# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paperclip_archive_processor}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sleistner"]
  s.date = %q{2011-02-17}
  s.description = %q{
    Extract paperclip archive attachments to file or S3.

    Usage:

    has_attached_file :archive,
                      :url  => '/assets/games/assets/:id/archive.:extension',
                      :extract_archive => true
  }
  s.email = %q{sleistner@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/paperclip_archive_processor.rb",
    "lib/paperclip_archive_processor/extractor.rb",
    "lib/paperclip_archive_processor/integration.rb",
    "lib/paperclip_archive_processor/processor.rb",
    "lib/paperclip_archive_processor/zip_util.rb",
    "paperclip_archive_processor.gemspec",
    "public/system/archives/1/original/1",
    "public/system/archives/1/original/2",
    "public/system/archives/1/original/3",
    "public/system/archives/1/original/4",
    "public/system/archives/1/original/5",
    "public/system/archives/1/original/5x.zip",
    "test/database.yml",
    "test/debug.log",
    "test/extractor_test.rb",
    "test/fixtures/1x.zip",
    "test/fixtures/2x.zip",
    "test/fixtures/3x.zip",
    "test/fixtures/4x.zip",
    "test/fixtures/5x.zip",
    "test/helper.rb",
    "test/integration_test.rb",
    "test/processor_test.rb"
  ]
  s.homepage = %q{http://github.com/sleistner/paperclip_archive_processor}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extract paperclip archive attachments to file or S3.}
  s.test_files = [
    "test/extractor_test.rb",
    "test/helper.rb",
    "test/integration_test.rb",
    "test/processor_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, ["~> 2.3.3"])
      s.add_runtime_dependency(%q<zip>, [">= 2.0.2"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<redgreen>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, ["~> 1.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<paperclip>, ["~> 2.3.3"])
      s.add_dependency(%q<zip>, [">= 2.0.2"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<redgreen>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<paperclip>, ["~> 2.3.3"])
    s.add_dependency(%q<zip>, [">= 2.0.2"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<redgreen>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

